{{- if .Values.rbac.create -}}
{{- if .Values.monitoring.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pipeops-agent.fullname" . }}-monitoring-proxy
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "pipeops-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "pipeops-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pipeops-agent.fullname" . }}-monitoring-proxy
{{- end }}
{{- end }}
